workspace 'CCC-TV'
#platform :ios, '9.0'
xcodeproj 'CCC-TV/CCCtv.xcodeproj'

use_frameworks!

target :CCCtv do
    pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
end

target :'CCCtv-Tests' do
	pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
end
